service: admin-suspender

provider:
  name: aws
  runtime: python2.7
  region: us-east-1
  stage: dev
  tags:
    project: admin-suspender
  deploymentBucket:
    name: serverless-apps
    serverSideEncryption: AES256
  deploymentPrefix: admin-suspender-serverless

plugins:
  - serverless-python-requirements

functions:
  suspend_admin:
    handler: handler.suspend_admin
    timeout: 300 # 5 minutes
    role: arn:aws:iam::1234567890:role/admin-suspender
    events:
      - sqs: arn:aws:sqs:us-east-1:1234567890:suspend_service_account
    vpc:
      securityGroupIds:
        - sg-123abc
      subnetIds:
        - subnet-1234567abcde
